name: spritewidget
description: SpriteWidget is an open source toolkit for building complex, high performance animations and 2D games with Flutter.
version: 0.9.20
author: Viktor Lidholt <viktorlidholt@gmail.com>
homepage: http://spritewidget.com
environment:
  sdk: ">=2.4.0 <3.0.0"
  flutter: ">=1.7.8 <2.0.0"
dependencies:
  flutter:
    sdk: flutter
